[tool.poetry]
name = "agym"
version = "0.1.0"
description = ""
authors = ["Anton Novikov <thescir@yandex.ru>"]

[tool.poetry.dependencies]
python = "3.8"
pygame = "^2.1.2"
numpy = "^1.22.1"
dependency-injector = "^4.37.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
